/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/clouds/clouds.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function cloudcluster(props) {
  const { nodes, materials } = useGLTF('/clouds.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Node.geometry} material={materials.mat21} />
    </group>
  )
}

useGLTF.preload('./models/clouds/clouds.glb')
