/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\models\clouds\Flying saucer.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ufo(props) {
  const { nodes, materials } = useGLTF('/Flying saucer.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Node.geometry} material={materials.MAIN} />
    </group>
  )
}

useGLTF.preload('./models/clouds/Flying saucer.glb')
