/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/jet/jet.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function jet(props) {
  const { nodes, materials } = useGLTF('/jet.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Jet_mesh.geometry} material={materials.Jet_mat1} />
    </group>
  )
}

useGLTF.preload('./models/jet/jet.glb')
